Update redux initial state naming of properties
vitor-afonso/cozinha-da-sandra-client pull request #30
Opened 2023-03-21 19:50 UTC by vitor-afonso

**PR description**
- Updates naming of some initial state properties and respective places where there are in being used

2023-03-21 20:19 UTC, zandrastr commented on src/pages/EditOrderPage.js
> +import { addToCart, clearCart, setItemAmount, handlefreeDelivery } from '../redux/features/items/itemsSlice';
`handlefreeDelivery` 
This should be camel case like this: `handleFreeDelivery`

2023-03-21 20:24 UTC, zandrastr requested changes
`handlefreeDelivery` 
I think this should be camelCase like this: `handleFreeDelivery`

2023-03-21 22:21 UTC, gustavosf2003 approved these changes

2023-03-22 10:47 UTC, zandrastr approved these changes

2023-03-22 10:47 UTC, merged